<?php

namespace Dark\Core\Db;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-19 at 22:41:28.
 */
class DbPoolTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DbPool
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new DbPool;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @covers Dark\Core\Db\DbPool::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Dark\Core\Db\DbPool::get
     * @todo   Implement testGet().
     */
    public function testGet() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}
